### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by JGallardo** [Cotidia/django-contenttools-demo#1]
Is this an error?

```
git clone https://github.com/Cotidia/django-contenttools-demo.git
cd contenttools_django
```

should it not be 

```
cd django-contenttools-demo
```

otherwise where in your tutorial did you add a project or say to make a directory named **contenttools_django**

**Comment by guillaumepiot** [comment]
Hi @JGallardo, that is an error indeed, I wonder how I got it so wrong!

The doc is now corrected.

Thank you.
